# 판다스

In [1]:
import pandas as pd
pd.__version__

'2.3.3'

### 시리즈 객체

생성: 리스트, 딕셔너리 등 시퀀스형 데이터로부터 생성할 수 있습니다.


일반적 방법: 보통 데이터프레임을 먼저 만들고 특정 열을 추출하여 시리즈를 얻는 방식이 많이 쓰입니다.


주요 속성: 


s.dtype: 데이터 타입 반환 


s.shape: 데이터 구조를 튜플로 반환 


s.size: 요소의 총 개수 반환 


s.name: 시리즈의 이름 반환 


s.index: 인덱스 반환 


s.values: 값을 넘파이 배열로 반환

In [23]:
# 기본 문법
# series = pd.Series(sequence, dtype, index, name)

# 리스트로부터 생성
numbers = [1, 2, 3, 4, 5]
list_sr = pd.Series(numbers)

# 속성 확인
print(list_sr.dtype, list_sr.shape, list_sr.size)
print(list_sr.index)
print(list_sr.values)
print(list_sr)

int64 (5,) 5
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [26]:
# 딕셔너리로부터 생성
dict_data = {"a":1, "b":2, "c":3, "d":4, "e":5}
dict_sr = pd.Series(dict_data)
print(dict_sr.dtype, dict_sr.shape, dict_sr.size)
print(dict_sr.index)
print(dict_sr.values)
print(dict_sr)

int64 (5,) 5
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1 2 3 4 5]
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
# dtype 및 속성 지정
sr1 = pd.Series(numbers, dtype=float) 
import numpy as np
sr2 = pd.Series(numbers, dtype=np.float32)
print(sr2)
# 속성 수정 및 추가
sr1.index = ['a', 'b', 'c', 'd', 'e'] 
sr1.name = 'MySeries'
sr1
# 컬럼명 및 타입 변경 문법
# new_df = org_df.rename(columns={기존이름: 새이름}) 
# new_df = org_df.astype(columns={컬럼명: 타입})

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float32

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: MySeries, dtype: float64

In [5]:
chars = 'a b c d e'.split()
sr3 = pd.Series(numbers, index=chars, name='MySeries')
sr3

a    1
b    2
c    3
d    4
e    5
Name: MySeries, dtype: int64

In [6]:
sr3.index, sr3.values

(Index(['a', 'b', 'c', 'd', 'e'], dtype='object'), array([1, 2, 3, 4, 5]))

In [7]:
# 딕셔너리로 만들기
s = pd.Series({'a':1,'b':2,'c':3,'d':4, 'e':5})
print(s.dtype, s.shape, s.size, s.name)
print(s.values)
print(s)

int64 (5,) 5 None
[1 2 3 4 5]
a    1
b    2
c    3
d    4
e    5
dtype: int64

### 데이터프레임

데이터프레임 속성: 


df.shape: 행과 열의 개수 


df.columns: 열 이름 목록 


df.dtypes: 각 열의 데이터 타입 


데이터 수정: rename()으로 컬럼명을 바꾸고, astype()으로 데이터 타입을 변경합니다

In [8]:
numbers = [1,2,3,4,5]
pd1 = pd.DataFrame(numbers)
pd1

   0
0  1
1  2
2  3
3  4
4  5

In [9]:
pd2 = pd.DataFrame(numbers, columns=['number'])
pd2

   number
0       1
1       2
2       3
3       4
4       5

In [10]:
# 2차원 리스트로부터 생성
score = [['정약용', 70, 80, 100],
         ['이순신', 100, 80, 70],
         ['이율곡', 90, 95, 98]]
score_df = pd.DataFrame(score)
score_df

     0    1   2    3
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   98

In [11]:
score_df.columns = ['이름', '영어', '수학', '국어']
score_df.index = ['a', 'b', 'c']
score_df

    이름   영어  수학   국어
a  정약용   70  80  100
b  이순신  100  80   70
c  이율곡   90  95   98

In [ ]:
print(score_df.shape, score_df.index, score_df.columns, score_df.dtypes, score_df.values, sep='\n')

((3, 4),
 Index(['a', 'b', 'c'], dtype='object'),
 Index(['이름', '영어', '수학', '국어'], dtype='object'),
 이름    object
 영어     int64
 수학     int64
 국어     int64
 dtype: object,
 array([['정약용', 70, 80, 100],
        ['이순신', 100, 80, 70],
        ['이율곡', 90, 95, 98]], dtype=object))

In [37]:
# 딕셔너리로부터 생성
score_dict = {'이름': ['정약용', '이순신', '이율곡', '홍길동'],
              '국어': [70, 100, 90, 85],
              '영어': [80, 80, 95, 100],
              '수학': [100, 70, 90, 90]}
score_df2 = pd.DataFrame(score_dict)
# 수정 예시 - 객체 반환하는 함수들임. 원본적용 x, 하려면 inplace=True 옵션 넣으면됨
score_df2.rename(columns={'이름':'name', '국어':'kerean'})
score_df2.astype({'국어': float}) 
score_df2['국어'].dtype

dtype('int64')

In [39]:
# 열 추가 및 연산
score_df2['사회'] = [85, 88, 92, 96]
# score_df2['총점'] = score_df2.국어 + score_df2.영어 + score_df2.수학 + score_df2.사회 이렇게 해도됨 이미 있는 컬럼만.
score_df2['총점'] = score_df2['국어'] + score_df2['영어'] + score_df2['수학'] + score_df2['사회']
score_df2['평균'] = score_df2.총점 / 4
score_df2

    이름   국어   영어   수학  사회   총점     평균
0  정약용   70   80  100  85  335  83.75
1  이순신  100   80   70  88  338  84.50
2  이율곡   90   95   90  92  367  91.75
3  홍길동   85  100   90  96  371  92.75

In [ ]:
# 수식 기반 열 추가 예시
x = [0, 1, 2, 3, 4, 5]
y = [0, 2, 4, 6, 8, 10]
df = pd.DataFrame()
df['x'] = x 
df['y'] = y 
df['x*y'] = df['x'] * df['y']
df

   x   y  x*y
0  0   0    0
1  1   2    2
2  2   4    8
3  3   6   18
4  4   8   32
5  5  10   50

In [ ]:
# 삭제 및 초기화 (inplace=True)
score_df.drop(['이름'], axis=1) # 열 삭제 - 컬럼명으로 삭제
score_df.drop(['a', 'b'], axis=0) # 행 삭제 - 인덱스로 삭제 디폴트는 행
score_df.reset_index(drop=True) # 인덱스 초기화 및 기존 인덱스 삭제

    이름   영어  수학   국어
0  정약용   70  80  100
1  이순신  100  80   70
2  이율곡   90  95   98

In [52]:
# 열(column) 접근 - select
score_df2['이름']
score_df2.이름
print(score_df2[['이름', '총점', '평균']]) #boolean 인덱싱 비슷한 느낌
# 행 슬라이싱. 행하나로 접근은 안됨
df[1:3]

    이름   총점     평균
0  정약용  335  83.75
1  이순신  338  84.50
2  이율곡  367  91.75
3  홍길동  371  92.75

   x  y  x*y
1  1  2    2
2  2  4    8

In [18]:
# Boolean Indexing(행 추출) - where 조건걸기
score_df2[score_df2['수학'] > 80]
score_df2[(score_df2['수학'] > 80) & (score_df2['영어'] < 90)]
score_df2[score_df2['이름'].isin(['정약용', '이순신'])]

    이름   국어  영어   수학  사회   총점     평균
0  정약용   70  80  100  85  335  83.75
1  이순신  100  80   70  88  338  84.50

In [53]:
# df.loc, df.iloc
print(score_df2.loc[0])
print(score_df2.loc[0,'국어'])
print(score_df2.loc[0, ['이름', '총점']])
print(score_df2.loc[0:2, '국어':'수학']) # 끝점포함

print(score_df2.iloc[0,0])
print(score_df2.iloc[0:1,0:3]) # 끝점제외

이름      정약용
국어       70
영어       80
수학      100
사회       85
총점      335
평균    83.75
Name: 0, dtype: object
70
이름    정약용
총점    335
Name: 0, dtype: object
    국어  영어   수학
0   70  80  100
1  100  80   70
2   90  95   90
정약용
    이름  국어  영어
0  정약용  70  80

외부 파일 로딩다양한 형식의 파일을 판다스 객체로 변환하여 분석을 시작합니다.

CSV 로드: pd.read_csv('파일경로', sep=',', encoding=...) 형식을 사용합니다.

JSON 로드: pd.read_json('파일경로', encoding=...) 형식을 사용합니다.

데이터 확인을 위한 주요 메서드데이터의 전체적인 구조와 누락된 값(결측치) 등을 빠르게 파악할 때 사용합니다.

앞/뒤 데이터 확인: head(n)는 상위 5개(기본값), tail(n)은 하위 5개의 행을 출력합니다.

크기 및 개수: shape는 (행, 열)의 크기를 튜플로 반환하며, len()은 전체 데이터의 개수(행의 수)를 알려줍니다.

정보 요약: info()를 통해 각 열의 데이터 개수와 결측치(null, NaN) 존재 여부, 데이터 타입을 한눈에 확인합니다.

기술 통계: describe()는 숫자형(float, int) 열에 대해서만 평균, 표준편차, 최솟값, 최댓값 등의 통계치를 계산해 줍니다.

값별 빈도: value_counts()는 특정 열의 데이터 값들이 각각 몇 개씩 들어있는지 집계합니다.

In [20]:
import pandas as pd

# 1. 파일 불러오기 [cite: 440]
sample_df = pd.read_csv('./data/sample_data.csv')

# 2. 상단 및 하단 데이터 확인 (각 3개씩)
print(sample_df.head(3))
print(sample_df.tail(3))

# 3. 데이터프레임 구조 확인
print("구조(행, 열):", sample_df.shape)
print("전체 데이터 개수:", len(sample_df))

# 4. 컬럼별 정보 및 결측치 확인
sample_df.info()

      Name   Age Gender         City
0    Alice  24.0      F     New York
1      Bob   NaN      M  Los Angeles
2  Charlie  22.0      M          NaN
     Name   Age Gender      City
4  Edward   NaN      M   Houston
5   Alice  24.0      F  New York
6   Susan  32.0      F   Houston
구조(행, 열): (7, 4)
전체 데이터 개수: 7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Age     5 non-null      float64
 2   Gender  7 non-null      object
 3   City    6 non-null      object
dtypes: float64(1), object(3)
memory usage: 352.0+ bytes

In [21]:
# 5. 수치형 데이터 통계 요약
print(sample_df.describe())

# 6. 특정 컬럼의 값 빈도수 확인 (예: 'City' 컬럼) 
sample_df['City'].value_counts()

             Age
count   5.000000
mean   26.200000
std     4.147288
min    22.000000
25%    24.000000
50%    24.000000
75%    29.000000
max    32.000000

City
New York       2
Houston        2
Los Angeles    1
Chicago        1
Name: count, dtype: int64