In [17]:
import pandas as pd
import numpy as np

In [52]:
df_jobkorea = pd.read_json('./data/extracted_jobs_result_jobkorea.json')
df_saramin = pd.read_json('./data/extracted_jobs_result_saramin.json')
df_wanted = pd.read_json('./data/extracted_jobs_result_wanted.json')
len(df_jobkorea), len(df_saramin), len(df_wanted)

(10107, 25950, 4404)

In [4]:
df_jobkorea.columns, df_wanted.columns

(Index(['공고번호', '회사명', '공고제목', '연차/경력', '지역', '기술스택/분야', '마감일', '상세내용',
        'hard_skills', 'soft_skills', 'preferences', 'culture_keywords',
        'urgency_score', 'urgency_reason'],
       dtype='object'),
 Index(['job_id', 'tag_id', 'year_filter', 'company', 'position', 'main_tasks',
        'requirements', 'preferred', 'skill_tags', 'location', 'scraped_date',
        'hard_skills', 'soft_skills', 'preferences', 'culture_keywords',
        'urgency_score', 'urgency_reason'],
       dtype='object'))

In [54]:
df_wanted_na = df_wanted.copy()
df_wanted_na['location'] = df_wanted_na['location'].replace(np.nan, '경기도 용인시 처인구', regex=True)
df_wanted_na['location'].isna().sum()

np.int64(0)

In [50]:
df_wanted_na[df_wanted_na['location'].isna()]

Empty DataFrame
Columns: [location]
Index: []

In [34]:
len(df_jobkorea_na[df_jobkorea_na['지역'].isna()]), len(df_jobkorea_na[df_jobkorea_na['지역'] == ''])

(23, 0)

In [31]:
df_jobkorea_na[df_jobkorea_na['지역'] == '']

Empty DataFrame
Columns: [공고번호, 회사명, 공고제목, 연차/경력, 지역, 기술스택/분야, 마감일, 상세내용, hard_skills, soft_skills, preferences, culture_keywords, urgency_score, urgency_reason]
Index: []

In [35]:
df_jobkorea_na[df_jobkorea_na['지역'].isna()]

,공고번호,회사명,공고제목,연차/경력,지역,기술스택/분야,마감일,상세내용,hard_skills,soft_skills,preferences,culture_keywords,urgency_score,urgency_reason
476,49333913,㈜비트,[일본 도쿄] 개발자 모집(경력 2년이상),경력2년↑,<NA>,"모바일앱개발, 솔루션, CRM, 소프트웨어개발",2일 전 등록,㈜비트 [일본 도쿄] 개발자 모집(경력 2년이상) ⭐ 95명 이상 찜한 기업 📜 설...,"[AWS, JAVA, PHP, Python, React, Spring Boot, T...","[성실성, 적응성, 창의성, 협동심, 계획성]","[일본어가능자, JLPT 2급 이상, 정보처리산업기사, 정보통신공학과 전공, 컴퓨터...","[리프레시 휴가, 자기개발 지원, 야간근로수당, 탄력근무제, 연금·보험, 주5일제,...",1,마감일이 상시채용으로 명시되어 있어 채용의 시급성이 낮습니다.
971,49232681,SEAGILE.LTD,(동경 및 시마네) WebApplication개발자모집 (JAVA),경력1년↑,<NA>,"모바일앱개발, SI개발, 솔루션, SI, 인터페이스, 소프트웨어개발",05/22(금) 등록,SEAGILE.LTD (동경 및 시마네) WebApplication개발자모집 (JA...,"[HTML, JAVA, MySQL, PHP, Ruby]","[성실성, 성장지향성, 꼼꼼함, 협동심, 계획성]","[경력 1년 이상, 초대졸 이상, 일본어(JPT 450점 이상 또는 JLPT 3급 ...","[성과급, 자격증취득지원, 사내 외국어강좌 운영, 연금·보험, 주5일제, 워크샵/M...",3,"마감일이 10일 정도 남았으며, 특별한 급구 문구나 파격적인 보상 조건이 명시되지 ..."
1232,49152632,㈜DEVFOX,[일본도쿄근무][신입/경력][정사원] JAVA 웹개발자/시스템 엔지니어 모집,경력무관,<NA>,"SI개발, SI, 소프트웨어개발",05/12(화) 등록,㈜DEVFOX [일본도쿄근무][신입/경력][정사원] JAVA 웹개발자/시스템 엔지니...,"[AWS, Git, JAVA, Javascript, JSP, Oracle, Reac...","[성실성, 성장지향성, 꼼꼼함, 적응성, 협동심]","[관련 학과 전공자, 일본어 가능자, JPT, JLPT, 정보처리산업기사]","[도서 구입비 지원, 헬스비, 장기근속 포상, 교통비, 인센티브, 기숙사 지원, 연...",3,"마감일이 약 19일 남아 있으며, 특별한 긴급 채용이나 파격적인 보상 문구가 없는 ..."
1729,49325857,MARU株式?社,마루와 함께할 프로그래머/시스템엔지니어 모집(일본 도쿄근무),경력무관,<NA>,"GUI, 시스템운영, SI개발",3일 전 등록,MARU株式?社 마루와 함께할 프로그래머/시스템엔지니어 모집(일본 도쿄근무) 🌃 야...,"[AWS, C#, JAVA, Javascript, MariaDB, MySQL, Or...","[성취지향성, 협동심, 스트레스관리, 적응성, 성실성]","[일본어, JPT, JLPT, 신JLPT]","[야간근로수당, 장기근속수당, 주거비 지원, 연금·보험, 연차제도, 경조휴가, 체육...",3,"마감일이 약 19일 남았으며, 현재 5명의 지원자가 있는 일반적인 채용 상황입니다."
2494,48973482,㈜스톤비,스톤비에서 Web/APP엔지니어를 모집합니다.(동경근무),신입·경력,<NA>,"모바일앱개발, 솔루션, BI, SI",04/13(월) 등록,㈜스톤비 스톤비에서 Web/APP엔지니어를 모집합니다.(동경근무) ⭐ 78명 이상 ...,"[Android, iOS, JAVA, JSP, Oracle, Swift, TypeS...",[],"[일본어가능자, 해외근무 가능자, JLPT 2급 이상, 정보처리산업기사, 정보처리기...","[동경근무, 정규직, 수습 6개월, 계약직, 프리랜서, 야간근로수당, 연금, 보험]",2,"상시채용 공고로 명시되어 있으며, 즉시 출근이나 파격적인 보상 등 긴급성을 나타내는..."
2742,49348697,임장식,기존 서치펌 계정 연동,경력3년↑,<NA>,"악세서리디자인, 섬유디자인, 인터페이스, 공예디자인, 시스템운영, 네트워크관리, 서...",1일 전 등록,메뉴 건너뛰기 배너 최근 본 공고 39 최근 본 공고 총 건 닫기 페이지 상단으로 ...,[],[],"[경력 3년 이상, 대졸 이상]","[회사내규에 따름, 유럽 전지역]",3,시급성을 나타내는 구체적인 문구나 긴급 채용에 대한 언급이 없음.
3505,49343477,AM SOLUTION INC,"[급구] 미국 제조업체 IT 신입, 경력직 채용",신입·경력5년↑,<NA>,"IT컨설팅, 서버관리, 네트워크관리",2일 전 등록,"AM SOLUTION INC [급구] 미국 제조업체 IT 신입, 경력직 채용 ⭐ 2...","[시스템엔지니어, 네트워크관리, 서버관리, IT 개발자]",[],"[경력 5년 이상, 대졸이상 (졸업예정자 가능)]","[외국계, 주5일, 09:00 ~ 18:00, 미국 근무]",5,공고 제목에 [급구]가 명시되어 있어 채용의 시급성이 매우 높음.
4069,49177500,INTERLINE㈜,일본 도쿄 현지 근무 / 소프트웨어 개발자 모집 (정규직) / 인터라인 직접,신입·경력1년↑,<NA>,"데이터관리, 솔루션, 서버구축, 시스템운영, SI, 시스템분석, CRM, 네트워크관...",05/14(목) 등록,INTERLINE㈜ 일본 도쿄 현지 근무 / 소프트웨어 개발자 모집 (정규직) / ...,[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
4163,49000431,"Infosec Information Technology (Wuxi) co., Ltd.",[SK쉴더스 중국법인] 네트워크 보안 운영 전문가 모집,경력5년↑,<NA>,"방화벽, 네트워크보안, 보안소프트웨어, 보안관제, 네트워크 보안, 정보보안, 서버관...",04/16(목) 등록,"Infosec Information Technology (Wuxi) co., Ltd...",[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
4724,49149378,㈜ISFNET,"일본 현지 클라우드 엔지니어 모집(운영,보수,설계,구축)",경력1년↑,<NA>,"서버, 유지보수",05/11(월) 등록,"㈜ISFNET 일본 현지 클라우드 엔지니어 모집(운영,보수,설계,구축) 🏢 외국계(...",[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
4725,49149299,㈜ISFNET,"일본 현지 네트워크 엔지니어 모집(운영,보수,설계,구축)",경력1년↑,<NA>,"서버, 유지보수",05/11(월) 등록,"㈜ISFNET 일본 현지 네트워크 엔지니어 모집(운영,보수,설계,구축) 🏢 외국계(...",[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
4729,48976445,㈜ISFNET,일본 현지 인프라 운영 엔지니어 모집 (네트워크·서버·클라우드),경력1년↑,<NA>,"서버, 유지보수",04/14(화) 등록,㈜ISFNET 일본 현지 인프라 운영 엔지니어 모집 (네트워크·서버·클라우드) 🏢 ...,[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
5525,49344043,모비스체코,[현대모비스 체코 법인] IT 관리자 경력 채용,경력5년↑,<NA>,"비즈니스 시스템 (인프라/그룹웨어), 정보보안",1일 전 등록,모비스체코 [현대모비스 체코 법인] IT 관리자 경력 채용 ⭐ 129명 이상 찜한 ...,[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
5618,49249055,"Infosec Information Technology (Wuxi) co., Ltd.",[SK쉴더스 중국법인] SK그룹사 (SK 하이닉스) 물리보안 구축/운영 전문가,경력5년↑,<NA>,"물리보안 구축, 보안소프트웨어, 보안점검, 보안관제, 운영, 보안컨설팅",05/26(화) 등록,"Infosec Information Technology (Wuxi) co., Ltd...",[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
5620,49248568,삼성SDI헝가리법인,삼성SDI 헝가리법인 총무/정보보안 담당,경력무관,<NA>,"정보보안, 자동차부품, 행정",05/26(화) 등록,삼성SDI헝가리법인 삼성SDI 헝가리법인 총무/정보보안 담당 ⭐ 474명 이상 찜한...,[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
5686,49130668,"Infosec Information Technology (Wuxi) co., Ltd.",[SK쉴더스 중국법인] 정보보안(고급) 파트원 모집,경력7년↑,<NA>,"방화벽, 네트워크보안, 보안소프트웨어, 보안관제, 정보보안, 보안컨설팅, 네트워크관리",05/08(금) 등록,"Infosec Information Technology (Wuxi) co., Ltd...",[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
5688,49130679,"Infosec Information Technology (Wuxi) co., Ltd.",[SK쉴더스 중국법인] 정보보안(중급) 파트원 모집,경력3년↑,<NA>,"방화벽, 네트워크보안, 보안소프트웨어, 보안관제, 정보보안, 보안컨설팅, 네트워크관리",05/08(금) 등록,"Infosec Information Technology (Wuxi) co., Ltd...",[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
5689,49130619,"Infosec Information Technology (Wuxi) co., Ltd.",[SK쉴더스 중국법인] SK그룹사 (SK 하이닉스) EndPoint 보안 운영,경력3년↑,<NA>,"방화벽, 네트워크보안, 보안소프트웨어, 보안점검, 보안관제, 정보보안, 보안컨설팅",05/08(금) 등록,"Infosec Information Technology (Wuxi) co., Ltd...",[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
6372,49132512,동우전자,머신비전 개발자를 찾습니다.,경력3년↑,<NA>,"클라이언트, SI개발, 소프트웨어개발",05/08(금) 등록,동우전자 머신비전 개발자를 찾습니다. 🏢 외국계(외국 법인기타) 🍱 점심 식사 지원...,[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
6455,49341655,엘에스오토모티브테크놀로지스,2026년 6월 경력 수시채용 - 인도 재무,경력,<NA>,"부가세신고, 회로설계, 재무, PCB, 결산, 영업원가, 국내영업",2일 전 등록,엘에스오토모티브테크놀로지스 2026년 6월 경력 수시채용 - 인도 재무 상세요강 접...,[],[],[],[],3,채용 공고에 구체적인 정보가 없어 시급성을 정확히 평가하기 어려움.
6457,49341598,엘에스오토모티브테크놀로지스,2026년 6월 경력 수시채용 - 품질기동,경력,<NA>,"부가세신고, 회로설계, 재무, PCB, 결산, 영업원가, 국내영업",2일 전 등록,엘에스오토모티브테크놀로지스 2026년 6월 경력 수시채용 - 품질기동 상세요강 접수...,[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
7668,49265200,리서치센터,"QA Engineer, 과장급",경력5년↑,<NA>,검증,05/28(목) 등록,메뉴 건너뛰기 배너 최근 본 공고 24 최근 본 공고 총 건 닫기 페이지 상단으로 ...,[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.
7864,116835599,㈜제이알파트너/ 경력우대/ 연봉협상가능,품질관리/ 연봉3500이상/ 연봉협의/ 주간/ 교통비O/ 경력직,,<NA>,,05/26(화) 등록,오늘의 AI 추천 AI가 내 이력에 맞는 기회를 찾아드려요! 나만의 맞춤 정보 받기...,[],[],[],[],3,정보가 부족하여 채용의 시급성을 정확히 평가하기 어려움.

In [33]:
import pandas as pd
import re

# 테스트를 위한 임시 데이터프레임 생성
data = {
    "공고번호": ["49192253", "12345678"],
    "지역": ["", "서울 강남구"], # 하나는 비어있고, 하나는 채워져 있음
    "상세내용": [
        "...(생략)... 근무시간 주5일(월~금) 08:30 ~ 17:30 근무지주소 경남 김해시 대동면 대동산단4로 116-13 ... 경남>김해시 본 채용정보는 ...",
        "상세내용 텍스트입니다." # 이미 지역이 있으므로 처리 안 함
    ]
}
df_wanted = pd.DataFrame(data)

# 지역을 추출하는 함수
def extract_location_from_text(row):
    # 1. 이미 지역 값이 채워져 있다면 기존 값 그대로 유지
    if pd.notna(row['지역']) and str(row['지역']).strip() != '':
        return row['지역']
    
    text = str(row['상세내용'])
    
    # 2. '근무지주소 ' 뒤에 오는 '시/도 + 시/군/구' 패턴 찾기
    # 예: "근무지주소 경남 김해시..." -> "경남 김해시" 추출
    address_match = re.search(r'위치\s+([가-힣]+(?:도|광역시|특별시)?\s+[가-힣]+(?:시|군|구))', text)
    if address_match:
        return address_match.group(1)
        
    # 3. 위 패턴이 없다면 '경남>김해시' 같은 태그 패턴 찾기
    tag_match = re.search(r'([가-힣]+)>([가-힣]+(?:시|군|구))', text)
    if tag_match:
        return f"{tag_match.group(1)} {tag_match.group(2)}"
        
    # 4. 그래도 못 찾으면 NaN 반환
    return pd.NA
# apply 함수로 각 행에 적용하여 지역 컬럼 업데이트
df_jobkorea_na['지역'] = df_jobkorea_na.apply(extract_location_from_text, axis=1)

print(df_jobkorea_na[['공고번호', '지역']])

           공고번호         지역
0      49339872    울산 북구 외
1      49337167    대전 서구 외
2      49345320   서울 구로구 외
3      49336031   경기 파주시 외
4      49340230  서울 영등포구 외
...         ...        ...
10102  49356032   서울 송파구 외
10103  49349890   경기 하남시 외
10104  49354522     서울 송파구
10105  49352855     서울 강남구
10106  49360129     서울 종로구

[10107 rows x 2 columns]

In [38]:
df_wanted_na['location'].unique()

array(['서울특별시 서초구 강남대로407, 13층(오퍼스407)x', '서울 강남구 봉은사로30길 68',
       '서울특별시 서초구 서초대로27길 54,  1층', ..., '서울 금천구 가산디지털1로 181, 18층',
       '서울 서초구 서초대로 398, 20층', '경기 성남시 분당구 정자일로 95, 네이버1784'],
      dtype=object)

In [37]:
df_jobkorea_na['지역'].unique()

array(['울산 북구 외', '대전 서구 외', '서울 구로구 외', '경기 파주시 외', '서울 영등포구 외',
       '서울 종로구', '서울 강남구', '서울 송파구 외', '서울 용산구 외', '경기 오산시', '서울 마포구',
       '경기 성남시', '서울 마포구 외', '서울 중구', '서울 성동구 외', '경기 안양시 외', '서울 서초구',
       '서울 강남구 외', '경기 김포시 외', '경기 성남시 외', '서울 금천구', '서울 송파구', '서울 양천구',
       '경기 과천시', '대전 유성구 외', '서울 강서구', '경기 군포시 외', '인천 연수구 외', '부산 서구',
       '서울 성동구', '경기 시흥시', '경기 화성시', '전남 나주시', '강원 춘천시', '경기 고양시 외',
       '서울 중구 외', '인천 서구', '서울 영등포구', '경기 남양주시 외', '서울 서초구 외', '경기 안성시',
       '경기 용인시 외', '울산 중구', '강원 원주시', '서울 강서구 외', '서울 구로구', '경기 용인시',
       '서울 광진구', '서울 동작구 외', '경기 안양시', '경기 하남시', '서울', '서울 종로구 외',
       '서울 관악구 외', '서울 전지역', '충남 보령시', '서울 금천구 외', '인천 연수구', '서울 강동구',
       '경기 고양시', '서울 성북구', '충북 청주시', '서울 용산구', '경기 수원시', '서울 동작구',
       '경기 평택시', '경기 김포시', '경기 의왕시', '세종 전지역', '경기 전지역 외', '울산 울주군 외',
       '광주 북구', '경기 양주시', '서울 동대문구 외', '부산 해운대구', '서울 강동구 외', '경기 화성시 외',
       '인천 중구', '인천 남동구', '경기 이천시', '경기 구리시', '경기 파주시', '충남 아산시',
       '경기 과천시 외', '경기 광명시', '대전 유성구', '부산 사상구', '경기 군포시', '경북 구미시', <NA>,
       '대전 동구', '광주 광산구', '부산 강서구', '울산 남구', '전남 여수시', '인천 부평구',
       '서울 서대문구', '대구 서구', '서울 강북구', '대구 동구', '부산 남구', '충청남도 천안시',
       '대전 서구', '광주 서구', '충남 천안시', '경기 의정부시', '부산 해운대구 외', '전북 완주군',
       '경기 안산시', '경기 광주시', '전북 전주시', '경기 남양주시', '대전 대덕구', '제주 제주시',
       '광주 남구', '부산 부산진구', '광주 동구', '동경도 신쥬쿠구', '경남 창원시', '경기 부천시',
       '서울 중랑구', '서울 관악구', '대구 달서구 외', '전북 익산시', '대구 수성구', '인천 중구 외',
       '전국', '대구 달서구', '충남 청양군', '대전 중구', '서울 은평구', '대구 수성구 외', '대구 남구',
       '세종 전지역 외', '경기 부천시 외', '서울 광진구 외', '충북 증평군', '울산 울주군', '대전 중구 외',
       '제주 서귀포시', '서울 전지역 외', '경기 전지역', '경기 수원시 외', '부산 부산진구 외',
       '경기 의왕시 외', '효고현 고베시', '경남 김해시', '인천 부평구 외', '경북 문경시', '대구 동구 외',
       '서울 서대문구 외', '경기 안성시 외', '대구 달성군', '울산 동구', '부산 금정구', '도쿄도 신주쿠구',
       '경남 사천시', '부산 연제구', '경북 김천시', '울산 북구', '서울 양천구 외', '경기 하남시 외',
       '경북 포항시', '경북 안동시', '대구 중구 외', '서울 동대문구', '경기 이천시 외', '충남 논산시',
       '중동 아시', '인천 전지역', '서울 노원구', '경기', '인천 서구 외', '전남 무안군', '경상북도 상주시',
       '경기 평택시 외', '부산 전지역', '경북 경산시', '서울 성북구 외', '제주특별자치도 제주시',
       '부산 남구 외', '대구 달성군 외', '울산 남구 외', '대전 전지역', '전남 순천시', '경상북도 구미시',
       '경남 양산시', '대구 중구', '경기 안산시 외', '강원 평창군', '충청남도 아산시', '충남 계룡시',
       '강원 강릉시', '충북 진천군', '전남 해남군', '서울 중랑구 외', '인천 미추홀구', '인천 계양구',
       '부산 동구', '충북 음성군', '부산 북구', '오사카시 츄오구', '경기 여주시', '서울 은평구 외',
       '동경도 신쥬구', '대구 북구', '서울 도봉구', '충남 홍성군', '전남 광양시', '부산 동구 외',
       '인천 남동구 외', '경북 칠곡군', '충청북도 청주시', '경상남도 사천시', '북아메리카 멕시', '부산 중구',
       '경남 진주시', '강원 정선군', '강원 횡성군', '중동 인도네시', '부산 사하구', '강원 삼척시',
       '경기 포천시', '충남 당진시', '부산 동래구', '강원 홍천군', '강원 철원군', '베트남 호치민시',
       '충청북도 진천군', '인천 동구', '전남 영암군', '부산 기장군', '경남 거제시', '충북 충주시',
       '인천 전지역 외', '인천 미추홀구 외', '울산 동구 외', '강원특별자치도 양양군', '충남 공주시',
       '전남 장성군', '광주 남구 외', '부산 영도구', '경기 시흥시 외', '부산 수영구', '광주 동구 외',
       '경기 광명시 외', '경북 예천군', '대전 대덕구 외', '충북 제천시', '전남 화순군', '미국 미시',
       '경기 동두천시', '경기 양주시 외', '경기 포천시 외', '전북 군산시', '경기 광주시 외',
       '인천 계양구 외', '전북특별자치도 군산시', '대구 전지역 외', '부산 전지역 외', '광주 전지역 외',
       '부산 사상구 외', '경북 경주시', '광주 서구 외', '충남 예산군', '대전 동구 외', '충남 금산군',
       '경기 양평군 외', '부산 사하구 외', '대구 서구 외', '광주 북구 외', '경기 오산시 외',
       '서울 강북구 외', '인천 동구 외', '강원 양양군', '강원특별자치도 춘천시', '광주 광산구 외',
       '경기 의정부시 외', '경기 구리시 외', '울산 전지역 외', '부산 연제구 외', '서울 노원구 외',
       '강원 동해시', '부산 수영구 외', '전북 김제시', '광주 전지역', '전남 담양군', '경기 가평군', '인천',
       '경기 동두천시 외', '부산 강서구 외', '충청남도 예산군'], dtype=object)

In [71]:
import pandas as pd
import numpy as np
import re

# 질문에서 주신 데이터 일부 샘플링
data = [
    '울산 북구 외', '대전 서구 외', '서울 구로구 외', '서울 종로구', '서울 전지역',
    '경기 전지역 외', '세종 전지역 외', '동경도 신쥬쿠구', '효고현 고베시', 
    '충청남도 천안시', '강원특별자치도 춘천시', '<NA>', '전국', '전북 완주군'
]
df_job = pd.DataFrame({'location': data})

# 1. 시/도 명칭 통일 사전 (기존과 동일)
SIDO_MAP = {
    '서울특별시': '서울', '서울시': '서울', '서울': '서울',
    '경기도': '경기', '경기': '경기',
    '인천광역시': '인천', '인천시': '인천', '인천': '인천',
    '부산광역시': '부산', '부산시': '부산', '부산': '부산',
    '대구광역시': '대구', '대구시': '대구', '대구': '대구',
    '광주광역시': '광주', '광주시': '광주', '광주': '광주',
    '대전광역시': '대전', '대전시': '대전', '대전': '대전',
    '울산광역시': '울산', '울산시': '울산', '울산': '울산',
    '세종특별자치시': '세종', '세종시': '세종', '세종': '세종',
    '강원특별자치도': '강원', '강원도': '강원', '강원': '강원',
    '충청북도': '충북', '충북': '충북',
    '충청남도': '충남', '충남': '충남',
    '전북특별자치도': '전북', '전라북도': '전북', '전북': '전북',
    '전라남도': '전남', '전남': '전남',
    '경상북도': '경북', '경북': '경북',
    '경상남도': '경남', '경남': '경남',
    '제주특별자치도': '제주', '제주도': '제주', '제주': '제주'
}

def clean_portal_location(address):
    # 1. 완전한 결측치 및 의미 없는 광역 데이터 처리
    if pd.isna(address) or str(address).strip() in ('', '<NA>', 'None', '전국'):
        return np.nan
        
    addr_str = str(address).strip()
    
    # 2. ⭐️ 핵심: 텍스트 끝에 붙은 ' 전지역', ' 외', ' 전지역 외'를 정규식으로 한 번에 제거
    # \s*: 공백 허용, (전지역)?: 있을 수도 있고 없을 수도 있음, (외)?: 있을 수도 있고 없을 수도 있음, $: 문자열 끝
    addr_str = re.sub(r'\s*(전지역)?\s*(외)?$', '', addr_str).strip()
    
    # 3. 공백 기준으로 분리
    parts = addr_str.split()
    if not parts:
        return np.nan
        
    sido = parts[0]
    
    # 4. 시/도 표준화 및 해외 주소(동경도, 효고현 등) 필터링
    standard_sido = SIDO_MAP.get(sido)
    
    # 사전에 없는 지역(해외 또는 오타)은 가차없이 버림 (지도 시각화 시 오류 방지)
    if not standard_sido:
        return np.nan
        
    # 5. 최종 텍스트 조립
    if len(parts) >= 2:
        sigungu = parts[1].replace(',', '')
        return f"{standard_sido} {sigungu}"
    else:
        # '서울 전지역'이 '서울'로 잘려나간 경우 여기로 들어옴
        return standard_sido

# 전처리 적용
df_jobkorea_na['location_clean'] = df_jobkorea_na['지역'].apply(clean_portal_location)

print("=== 잡코리아/사람인 패턴 전처리 결과 ===")
print(df_jobkorea_na[['지역', 'location_clean']])

=== 잡코리아/사람인 패턴 전처리 결과 ===
              지역 location_clean
0        울산 북구 외          울산 북구
1        대전 서구 외          대전 서구
2       서울 구로구 외         서울 구로구
3       경기 파주시 외         경기 파주시
4      서울 영등포구 외        서울 영등포구
...          ...            ...
10102   서울 송파구 외         서울 송파구
10103   경기 하남시 외         경기 하남시
10104     서울 송파구         서울 송파구
10105     서울 강남구         서울 강남구
10106     서울 종로구         서울 종로구

[10107 rows x 2 columns]

In [ ]:
df_jobkorea_na.dropna(subset=['location_clean'], inplace=True)
df_jobkorea_na['location_clean'].unique()

10025

In [75]:
df_jobkorea_na.to_json('jobkorea_clean_location.json', force_ascii=False, orient='records')

In [ ]:
df_jobkorea_na['지역'].unique()

array(['울산 북구 외', '대전 서구 외', '서울 구로구 외', '경기 파주시 외', '서울 영등포구 외',
       '서울 종로구', '서울 강남구', '서울 송파구 외', '서울 용산구 외', '경기 오산시', '서울 마포구',
       '경기 성남시', '서울 마포구 외', '서울 중구', '서울 성동구 외', '경기 안양시 외', '서울 서초구',
       '서울 강남구 외', '경기 김포시 외', '경기 성남시 외', '서울 금천구', '서울 송파구', '서울 양천구',
       '경기 과천시', '대전 유성구 외', '서울 강서구', '경기 군포시 외', '인천 연수구 외', '부산 서구',
       '서울 성동구', '경기 시흥시', '경기 화성시', '전남 나주시', '강원 춘천시', '경기 고양시 외',
       '서울 중구 외', '인천 서구', '서울 영등포구', '경기 남양주시 외', '서울 서초구 외', '경기 안성시',
       '경기 용인시 외', '울산 중구', '강원 원주시', '서울 강서구 외', '서울 구로구', '경기 용인시',
       '서울 광진구', '서울 동작구 외', '경기 안양시', '경기 하남시', '서울', '서울 종로구 외',
       '서울 관악구 외', '서울 전지역', '충남 보령시', '서울 금천구 외', '인천 연수구', '서울 강동구',
       '경기 고양시', '서울 성북구', '충북 청주시', '서울 용산구', '경기 수원시', '서울 동작구',
       '경기 평택시', '경기 김포시', '경기 의왕시', '세종 전지역', '경기 전지역 외', '울산 울주군 외',
       '광주 북구', '경기 양주시', '서울 동대문구 외', '부산 해운대구', '서울 강동구 외', '경기 화성시 외',
       '인천 중구', '인천 남동구', '경기 이천시', '경기 구리시', '경기 파주시', '충남 아산시',
       '경기 과천시 외', '경기 광명시', '대전 유성구', '부산 사상구', '경기 군포시', '경북 구미시', <NA>,
       '대전 동구', '광주 광산구', '부산 강서구', '울산 남구', '전남 여수시', '인천 부평구',
       '서울 서대문구', '대구 서구', '서울 강북구', '대구 동구', '부산 남구', '충청남도 천안시',
       '대전 서구', '광주 서구', '충남 천안시', '경기 의정부시', '부산 해운대구 외', '전북 완주군',
       '경기 안산시', '경기 광주시', '전북 전주시', '경기 남양주시', '대전 대덕구', '제주 제주시',
       '광주 남구', '부산 부산진구', '광주 동구', '동경도 신쥬쿠구', '경남 창원시', '경기 부천시',
       '서울 중랑구', '서울 관악구', '대구 달서구 외', '전북 익산시', '대구 수성구', '인천 중구 외',
       '전국', '대구 달서구', '충남 청양군', '대전 중구', '서울 은평구', '대구 수성구 외', '대구 남구',
       '세종 전지역 외', '경기 부천시 외', '서울 광진구 외', '충북 증평군', '울산 울주군', '대전 중구 외',
       '제주 서귀포시', '서울 전지역 외', '경기 전지역', '경기 수원시 외', '부산 부산진구 외',
       '경기 의왕시 외', '효고현 고베시', '경남 김해시', '인천 부평구 외', '경북 문경시', '대구 동구 외',
       '서울 서대문구 외', '경기 안성시 외', '대구 달성군', '울산 동구', '부산 금정구', '도쿄도 신주쿠구',
       '경남 사천시', '부산 연제구', '경북 김천시', '울산 북구', '서울 양천구 외', '경기 하남시 외',
       '경북 포항시', '경북 안동시', '대구 중구 외', '서울 동대문구', '경기 이천시 외', '충남 논산시',
       '중동 아시', '인천 전지역', '서울 노원구', '경기', '인천 서구 외', '전남 무안군', '경상북도 상주시',
       '경기 평택시 외', '부산 전지역', '경북 경산시', '서울 성북구 외', '제주특별자치도 제주시',
       '부산 남구 외', '대구 달성군 외', '울산 남구 외', '대전 전지역', '전남 순천시', '경상북도 구미시',
       '경남 양산시', '대구 중구', '경기 안산시 외', '강원 평창군', '충청남도 아산시', '충남 계룡시',
       '강원 강릉시', '충북 진천군', '전남 해남군', '서울 중랑구 외', '인천 미추홀구', '인천 계양구',
       '부산 동구', '충북 음성군', '부산 북구', '오사카시 츄오구', '경기 여주시', '서울 은평구 외',
       '동경도 신쥬구', '대구 북구', '서울 도봉구', '충남 홍성군', '전남 광양시', '부산 동구 외',
       '인천 남동구 외', '경북 칠곡군', '충청북도 청주시', '경상남도 사천시', '북아메리카 멕시', '부산 중구',
       '경남 진주시', '강원 정선군', '강원 횡성군', '중동 인도네시', '부산 사하구', '강원 삼척시',
       '경기 포천시', '충남 당진시', '부산 동래구', '강원 홍천군', '강원 철원군', '베트남 호치민시',
       '충청북도 진천군', '인천 동구', '전남 영암군', '부산 기장군', '경남 거제시', '충북 충주시',
       '인천 전지역 외', '인천 미추홀구 외', '울산 동구 외', '강원특별자치도 양양군', '충남 공주시',
       '전남 장성군', '광주 남구 외', '부산 영도구', '경기 시흥시 외', '부산 수영구', '광주 동구 외',
       '경기 광명시 외', '경북 예천군', '대전 대덕구 외', '충북 제천시', '전남 화순군', '미국 미시',
       '경기 동두천시', '경기 양주시 외', '경기 포천시 외', '전북 군산시', '경기 광주시 외',
       '인천 계양구 외', '전북특별자치도 군산시', '대구 전지역 외', '부산 전지역 외', '광주 전지역 외',
       '부산 사상구 외', '경북 경주시', '광주 서구 외', '충남 예산군', '대전 동구 외', '충남 금산군',
       '경기 양평군 외', '부산 사하구 외', '대구 서구 외', '광주 북구 외', '경기 오산시 외',
       '서울 강북구 외', '인천 동구 외', '강원 양양군', '강원특별자치도 춘천시', '광주 광산구 외',
       '경기 의정부시 외', '경기 구리시 외', '울산 전지역 외', '부산 연제구 외', '서울 노원구 외',
       '강원 동해시', '부산 수영구 외', '전북 김제시', '광주 전지역', '전남 담양군', '경기 가평군', '인천',
       '경기 동두천시 외', '부산 강서구 외', '충청남도 예산군'], dtype=object)

In [55]:
len(df_wanted_na)

4404

In [59]:
import pandas as pd

# 테스트용 예시 데이터셋


# 시/도 명칭을 2글자로 통일하기 위한 매핑 사전
SIDO_MAP = {
    '서울특별시': '서울', '서울시': '서울', '서울': '서울',
    '경기도': '경기', '경기': '경기',
    '인천광역시': '인천', '인천시': '인천', '인천': '인천',
    '부산광역시': '부산', '부산시': '부산', '부산': '부산',
    '대구광역시': '대구', '대구시': '대구', '대구': '대구',
    '광주광역시': '광주', '광주시': '광주', '광주': '광주',
    '대전광역시': '대전', '대전시': '대전', '대전': '대전',
    '울산광역시': '울산', '울산시': '울산', '울산': '울산',
    '세종특별자치시': '세종', '세종시': '세종', '세종': '세종',
    '강원특별자치도': '강원', '강원도': '강원', '강원': '강원',
    '충청북도': '충북', '충북': '충북',
    '충청남도': '충남', '충남': '충남',
    '전북특별자치도': '전북', '전라북도': '전북', '전북': '전북',
    '전라남도': '전남', '전남': '전남',
    '경상북도': '경북', '경북': '경북',
    '경상남도': '경남', '경남': '경남',
    '제주특별자치도': '제주', '제주도': '제주', '제주': '제주'
}

# 자주 나오는 구 이름을 미리 매핑해두기 (성남시 구별 상세 추가)
GU_TO_SIDO = {
    '강남구': '서울 강남구', '서초구': '서울 서초구', '마포구': '서울 마포구', 
    '영등포구': '서울 영등포구', '구로구': '서울 구로구', '금천구': '서울 금천구',
    '분당구': '경기 성남시 분당구', '수정구': '경기 성남시 수정구', '중원구': '경기 성남시 중원구', '판교': '경기 성남시 분당구'
}

def clean_wanted_location(address):
    # 1. 결측치 처리
    if pd.isna(address) or str(address).strip() == '':
        return None
        
    # 2. 공백을 기준으로 텍스트 분리
    parts = str(address).strip().split()
    
    # 3. 주소가 2단어 이상인 경우 (예: "서울특별시 서초구 ...")
    if len(parts) >= 2:
        sido = parts[0]
        
        # 접두사가 구 이름으로 시작하는 예외 처리 (예: "분당구 판교역로")
        if sido in GU_TO_SIDO:
            return GU_TO_SIDO[sido]
            
        sigungu = parts[1].replace(',', '') # 시군구 뒤에 혹시 붙어있을 쉼표 제거
        
        # 시/도 이름 통일 (사전에 없으면 원래 이름 유지)
        sido_standard = SIDO_MAP.get(sido, sido)
        
        # ⭐️ 성남시 예외 처리: 시군구가 '성남시'이고, 뒤에 단어가 더 있다면 구 이름까지 추출
        if sigungu == '성남시' and len(parts) >= 3:
            gu = parts[2].replace(',', '')
            return f"{sido_standard} {sigungu} {gu}"
        
        return f"{sido_standard} {sigungu}"
        
    # 4. 주소가 1단어밖에 없는 예외 상황
    elif len(parts) == 1:
        sido = parts[0]
        if sido in GU_TO_SIDO:
            return GU_TO_SIDO[sido]
        return SIDO_MAP.get(sido, sido)
        
    return address

# apply 함수를 사용해 전처리 적용 및 새로운 컬럼 생성
df_wanted_na['location_clean'] = df_wanted_na['location'].apply(clean_wanted_location)

print("=== 전처리 결과 ===")
print(df_wanted_na[['location', 'location_clean']])

=== 전처리 결과 ===
                                   location location_clean
0           서울특별시 서초구 강남대로407, 13층(오퍼스407)x         서울 서초구
1                         서울 강남구 봉은사로30길 68         서울 강남구
2                 서울특별시 서초구 서초대로27길 54,  1층         서울 서초구
3                      서울 강남구 강남대로 364, 17층         서울 강남구
4                     서울 강남구 테헤란로 151, 712호         서울 강남구
...                                     ...            ...
4399            경기 성남시 분당구 정자일로 95, 네이버1784     경기 성남시 분당구
4400  서울시 용산구 한강대로30길 25 (아스테리움 용산) 10층 딥파인         서울 용산구
4401             서초구 방배천로24길 7 이수초석빌딩 2층 플랭         서울 서초구
4402      서울특별시 강남구 테헤란로 218, AP Tower 13층          서울 강남구
4403                    서울 강남구 도산대로 318, 7층         서울 강남구

[4404 rows x 2 columns]

In [60]:
import pandas as pd

# 1. 대한민국 시/도 명칭으로 시작할 수 있는 모든 경우의 수(접두사)를 튜플로 정의합니다.
valid_sido_prefixes = (
    '서울', '경기', '인천', '부산', '대구', '광주', '대전', '울산', '세종', 
    '강원', '충북', '충청북', '충남', '충청남', '전북', '전라북', '전남', '전라남', 
    '경북', '경상북', '경남', '경상남', '제주'
)

# 2. 결측치를 제외하고(na=False), 위 접두사로 시작하지 않는(~) 행만 필터링합니다.
# 주의: 이 필터링은 원본 데이터인 'location' 컬럼을 기준으로 확인하는 것이 좋습니다.
outlier_mask = ~df_wanted_na['location_clean'].str.startswith(valid_sido_prefixes, na=False)

# 3. 추가로 빈칸이나 완전한 결측치(NaN)가 아닌 경우만 뽑아내어 진짜 '이상한 주소'만 남깁니다.
not_empty_mask = df_wanted_na['location_clean'].astype(str).str.strip() != ''
not_na_mask = df_wanted_na['location_clean'].notna()

final_outlier_mask = outlier_mask & not_empty_mask & not_na_mask

# 예외 데이터 확인
df_outliers = df_wanted_na[final_outlier_mask]

print(f"찾아낸 예외 데이터 개수: {len(df_outliers)}개")
print("=== 예외 데이터 목록 ===")
print(df_outliers[['location_clean']])
df_outliers['location_clean'].unique()

찾아낸 예외 데이터 개수: 295개
=== 예외 데이터 목록 ===
     location_clean
10       디지털로31길 12
32         테헤란로 142
60          강동구 성안로
63       디지털로31길 12
73        테헤란로7길 22
...             ...
4224        성남시 분당구
4264          리모트근무
4304        성남시 수정구
4376      유성구 테크노4로
4380        성남시 분당구

[295 rows x 1 columns]

array(['디지털로31길 12', '테헤란로 142', '강동구 성안로', '테헤란로7길 22', '수원시 권선구',
       '리모트근무', '서대문구 충정로', '금토로 80번길', '성동구 성수일로1길', '연수구 컨벤시아대로',
       '성동구 광나루로8길', '중구 칠패로', '성남시 분당구', '봉은사로37길 7-14(논현동', '중구 청계천로',
       '테헤란로20길 9', '3F, 343', '중구 을지로', '송파구 올림픽로', '재택', '중구 명동길',
       '성동구 성수일로', '종로구 율곡로6', '서대문구 이화여대길', '송파구 백제고분로41길', '여의공원로 115',
       '중구 세종대로', '중구 퇴계로', '관악구 남부순환로', '봉은사로 331', '성남시 창업로',
       '강남대로92길 19', '17, Gangnam-daero', '기장군 일광읍', '종로구 경희궁길36',
       '연수구 송도과학로', '성동구 왕십리로58', '왕십리로 115', '동구 동대구로', '논현동 192-19',
       '성남시 수정구', '마곡중앙8로3길 41', '하남시 미사대로', '분당스퀘어(서현역)', ': 경기도',
       '역삼동 센터필드타워', '용인시 수지구', '현대캐피탈 본사(서울', '대한민국 서울특별시',
       '패스트파이브 역삼1호점', '선릉역 부근', '상원12길 1', '성동구 성수이로20길', '테헤란로 201',
       '이천시 부발읍', '용산구', '논현동 106-8번지', '(06241) 서울', '드림플러스 강남점',
       '학동로 224', '안양시 동안구', 'Remote 근무(사무실', '언주로 609',
       '하남시 미사강변중앙로31번길', '을지로', '중구 한강대로', '위워크 역삼역', '종로구 종로6',
       '군포첨단산업2로 102', '수원시 영통구', '재택가능', '마방로 28', '양화로 19', '동구 중앙대로',
       '유성구 테크노4로'], dtype=object)

In [48]:
df_wanted_na['location_clean'].unique()

array(['서울 서초구', '서울 강남구', '서울 금천구', '경기 성남시 분당구', '경기 용인시', None],
      dtype=object)

In [63]:
import pandas as pd
import re

# 테스트용 데이터
dirty_data = ['디지털로31길 12', '테헤란로 142', '강동구 성안로', '테헤란로7길 22', '수원시 권선구', 
              '리모트근무', '서대문구 충정로', '금토로 80번길', '성동구 성수일로1길', '연수구 컨벤시아대로', 
              '성동구 광나루로8길', '중구 칠패로', '성남시 분당구', '봉은사로37길 7-14(논현동', '중구 청계천로', 
              '테헤란로20길 9', '3F, 343', '중구 을지로', '송파구 올림픽로', '재택', '중구 명동길', 
              '성동구 성수일로', '종로구 율곡로6', '서대문구 이화여대길', '송파구 백제고분로41길', '여의공원로 115', 
              '중구 세종대로', '중구 퇴계로', '관악구 남부순환로', '봉은사로 331', '성남시 창업로', 
              '강남대로92길 19', '17, Gangnam-daero', '기장군 일광읍', '종로구 경희궁길36', 
              '연수구 송도과학로', '성동구 왕십리로58', '왕십리로 115', '동구 동대구로', '논현동 192-19', 
              '성남시 수정구', '마곡중앙8로3길 41', '하남시 미사대로', '분당스퀘어(서현역)', ': 경기도', 
              '역삼동 센터필드타워', '용인시 수지구', '현대캐피탈 본사(서울', '대한민국 서울특별시', 
              '패스트파이브 역삼1호점', '선릉역 부근', '상원12길 1', '성동구 성수이로20길', '테헤란로 201', 
              '이천시 부발읍', '용산구', '논현동 106-8번지', '(06241) 서울', '드림플러스 강남점', 
              '학동로 224', '안양시 동안구', 'Remote 근무(사무실', '언주로 609', 
              '하남시 미사강변중앙로31번길', '을지로', '중구 한강대로', '위워크 역삼역', '종로구 종로6', 
              '군포첨단산업2로 102', '수원시 영통구', '재택가능', '마방로 28', '양화로 19', '동구 중앙대로', 
              '유성구 테크노4로']

df_dirty = pd.DataFrame({'location': dirty_data})

# 🛠️ 핵심: 도로명, 동이름, 주요 랜드마크를 시/도+시군구로 강제 매핑하는 사전
# 우선순위가 높은(상세한) 지역부터 먼저 검사하도록 구성합니다.
ADVANCED_MAPPING = {
    # 1. 재택/원격근무 (가장 먼저 처리)
    '원격근무': ['재택', '리모트', 'remote'],
    
    # 2. 서울 주요 구별 핵심 키워드 (IT 기업 밀집 지역 위주)
    '서울 강남구': ['강남', 'gangnam', '테헤란', '역삼', '논현', '선릉', '봉은사', '학동', '언주'],
    '서울 성동구': ['성동', '성수', '왕십리', '상원'],
    '서울 중구': ['중구', '칠패', '청계천', '명동', '을지로', '세종대로', '퇴계로'],
    '서울 송파구': ['송파', '백제고분', '올림픽로'],
    '서울 종로구': ['종로', '율곡', '경희궁'],
    '서울 마포구': ['마포', '양화'],
    '서울 영등포구': ['여의'],
    '서울 구로구': ['디지털로'],
    '서울 서대문구': ['서대문', '충정', '이화여대'],
    '서울 관악구': ['관악', '남부순환'],
    '서울 강서구': ['마곡'],
    '서울 강동구': ['강동', '성안로'],
    '서울 용산구': ['용산', '한강대'],
    '서울 서초구': ['서초'],
    # 3. 경기 주요 시별 핵심 키워드
    '경기 수원시': ['수원', '권선', '영통'],
    '경기 하남시': ['하남', '미사', '마방'],
    '경기 용인시': ['용인', '수지'],
    '경기 안양시': ['안양', '동안'],
    '경기 군포시': ['군포'],
    '경기 이천시': ['이천', '부발'],
    
    # 4. 기타 지역
    '인천 연수구': ['연수', '송도'],
    '대전 유성구': ['유성', '테크노'],
    '대구 동구': ['동대구'],
    '부산 기장군': ['기장', '일광'],
    
    # 5. 광역 단위 Fallback (디테일한 구를 못 찾았을 때)
    '서울': ['서울', 'seoul'],
    '경기': ['경기']
}

def rescue_location(address):
    if pd.isna(address):
        return None
        
    addr_str = str(address).lower() # 영어(Remote, Gangnam) 처리를 위해 소문자로 변환
    
    # 특수문자 및 불필요한 앞뒤 텍스트 1차 제거 (예: ': 경기도' -> '경기도')
    addr_str = re.sub(r'^\W+|\W+$', '', addr_str) 
    
    # 매핑 사전 순회하며 키워드 찾기
    for standard_loc, keywords in ADVANCED_MAPPING.items():
        for kw in keywords:
            # 키워드가 주소 텍스트 안에 포함되어 있으면 즉시 해당 표준 지역 반환
            if kw in addr_str:
                return standard_loc
                
    # 사전에 없으면 일단 원본 반환 (확인용)
    return address

# 적용
df_wanted_na['location_final'] = df_wanted_na['location_clean'].apply(rescue_location)

# 결과 확인용 출력
print(df_wanted_na[['location', 'location_clean', 'location_final']])

                                   location location_clean location_final
0           서울특별시 서초구 강남대로407, 13층(오퍼스407)x         서울 서초구         서울 서초구
1                         서울 강남구 봉은사로30길 68         서울 강남구         서울 강남구
2                 서울특별시 서초구 서초대로27길 54,  1층         서울 서초구         서울 서초구
3                      서울 강남구 강남대로 364, 17층         서울 강남구         서울 강남구
4                     서울 강남구 테헤란로 151, 712호         서울 강남구         서울 강남구
...                                     ...            ...            ...
4399            경기 성남시 분당구 정자일로 95, 네이버1784     경기 성남시 분당구             경기
4400  서울시 용산구 한강대로30길 25 (아스테리움 용산) 10층 딥파인         서울 용산구         서울 용산구
4401             서초구 방배천로24길 7 이수초석빌딩 2층 플랭         서울 서초구         서울 서초구
4402      서울특별시 강남구 테헤란로 218, AP Tower 13층          서울 강남구         서울 강남구
4403                    서울 강남구 도산대로 318, 7층         서울 강남구         서울 강남구

[4404 rows x 3 columns]

In [64]:
# 1. 1차 전처리가 정상적으로 끝난 데이터들이 가져야 할 올바른 접두사(시/도) 정의
# (clean_wanted_location 함수가 만들어낸 2글자 표준 이름들입니다)
valid_sido = ('서울', '경기', '인천', '부산', '대구', '광주', '대전', '울산', '세종', 
              '강원', '충북', '충남', '전북', '전남', '경북', '경남', '제주')

# 2. 1차 정제본(location_clean)을 그대로 복사해서 최종본(location_final) 뼈대 만들기
df_wanted_na['location_final'] = df_wanted_na['location_clean']

# 3. 2차 전처리가 필요한 '진짜 노이즈' 데이터 골라내기 (조건 마스크 생성)
# - location_clean 값이 정상적인 시/도로 시작하지 않고 (~)
# - 결측치나 빈 문자열이 아닌 경우
is_not_valid_sido = ~df_wanted_na['location_clean'].str.startswith(valid_sido, na=False)
is_not_empty = df_wanted_na['location_clean'].notna() & (df_wanted_na['location_clean'] != '')

dirty_mask = is_not_valid_sido & is_not_empty

# 4. .loc를 사용하여 dirty_mask 조건이 True인 행의 'location_final' 컬럼에만 2차 함수 덮어쓰기
df_wanted_na.loc[dirty_mask, 'location_final'] = df_wanted_na.loc[dirty_mask, 'location_clean'].apply(rescue_location)

# 5. 결과 확인 (어떻게 바뀌었는지 타겟 행들만 필터링해서 확인)
print("=== 2차 전처리로 구제된 데이터 확인 ===")
print(df_wanted_na.loc[dirty_mask, ['location', 'location_clean', 'location_final']])

=== 2차 전처리로 구제된 데이터 확인 ===
                                   location location_clean location_final
10    디지털로31길 12, 8층, 13층, 14층 (구로동, 태평양물산)     디지털로31길 12         서울 구로구
32                      테헤란로 142 아크플레이스 12층       테헤란로 142         서울 강남구
60                          강동구 성안로 7-13 2층        강동구 성안로         서울 강동구
63    디지털로31길 12, 8층, 13층, 14층 (구로동, 태평양물산)     디지털로31길 12         서울 구로구
73                                테헤란로7길 22      테헤란로7길 22         서울 강남구
...                                     ...            ...            ...
4224              성남시 분당구 판교로 242 PDC A동 9층        성남시 분당구        성남시 분당구
4264                                  리모트근무          리모트근무           원격근무
4304                 성남시 수정구 고등로4 고산빌딩 4,5층        성남시 수정구        성남시 수정구
4376                           유성구 테크노4로 17      유성구 테크노4로         대전 유성구
4380       성남시 분당구 판교역로 230, 삼환하이펙스 B동 704호        성남시 분당구        성남시 분당구

[295 rows x 3 columns]

In [65]:
df_wanted_na['location_final'].unique()

array(['서울 서초구', '서울 강남구', '인천 연수구', '서울 마포구', '경기 수원시', '서울 구로구',
       '서울 영등포구', '서울 송파구', '서울 관악구', '서울 성동구', '경기 용인시', '서울 마포대로',
       '서울 중구', '경기 성남시 수정구', '서울 용산구', '서울 강동구', '부산 중구', '서울 금천구',
       '경기 성남시 분당구', '서울 강남대로53길', '대구 달성군', '원격근무', '경기 파주시', '서울 강서구',
       '서울 서대문구', '금토로 80번길', '서울 강서구마곡중앙6로', '서울 종로구', '충남 천안시',
       '서울 동대문구', '경기 성남시 중원구', '경기 고양시', '경기 하남시', '성남시 분당구', '서울 성북구',
       '경기 광명시', '전북 전주시', '서울 광진구', '3F, 343', '경기 안산시', '부산 해운대구',
       '경기 남양주시', '경기 안양시', '인천 서구', '울산 중구', '서울 강남대로84길', '경기 의왕시',
       '대전 유성구', '서울 양천구', '제주 제주시', '경기 과천시', '부산 남구', '대전 서구', '광주 북구',
       '경북 포항시', '성남시 창업로', '부산 기장군', '경남 창원시', '인천 미추홀구', '서울 동작구',
       '대구 동구', '성남시 수정구', '충북 청주시', '경기 김포시', '경기 화성시', '서울전역',
       '분당스퀘어(서현역)', '경기', '서울 도봉구', '대구 수성구', '부산 수영구', '경기 시흥시',
       '전북 군산시', '경기 군포시', '대구 북구', '서울', '경기 구리시', '세종 조치원읍', '세종 가름로',
       '경기 성남시', '부산 동구', '경기 이천시', '서울숲코오롱디지털타워1차 604호', '대구 서구', None,
       '인천 계양구', '부산 진구', '경기 평택시', '경기 부천시', '부산 영도구', '서울 관악로',
       '대구 달서구', '경기 성남시 판교역로184', '세종 집현중앙2로', '경북 경산시', '인천 부평구',
       '동구 중앙대로', '부산 북구', '광주 동구', '울산 남구', '서울 장충단로', '대전 대덕구', '광주 서구'],
      dtype=object)

In [66]:
LAST_CHANCE_MAP = {
    '금토로 80번길': '경기 성남시 수정구',
    '성남시 분당구': '경기 성남시 분당구',
    '성남시 창업로': '경기 성남시 수정구',
    '분당스퀘어(서현역)': '경기 성남시 분당구',
    '서울 강서구마곡중앙6로': '서울 강서구',
    '서울 강남대로84길': '서울 강남구',
    '서울 강남대로53길': '서울 서초구', # 강남대로는 서초/강남이 섞여있지만 임의 지정
    '동구 중앙대로': '부산 동구', # 문맥상 부산일 확률이 높음 (또는 대구)
    '경기 성남시 판교역로184': '경기 성남시 분당구'
}

def final_polish(address):
    # 1. 결측치 또는 'None' 문자열 날리기 (NaN 반환)
    if pd.isna(address) or str(address) == 'None' or str(address).strip() == '':
        return np.nan
        
    addr_str = str(address).strip()
    
    # 2. 마지막 매핑 사전에 있으면 바로 치환
    for key, value in LAST_CHANCE_MAP.items():
        if key in addr_str:
            return value
            
    # 3. '원격근무'는 살려둠
    if addr_str == '원격근무':
        return addr_str
        
    # 4. 정규식을 이용해 텍스트 다듬기
    # 예: '서울 마포대로' -> '서울 마포구' 로 치환하기 어려운 경우, 
    # '마포'라는 단어가 들어가면 마포구로 강제 변환하는 식의 로직 추가
    if '서울' in addr_str and '마포' in addr_str: return '서울 마포구'
    if '서울' in addr_str and '강남' in addr_str: return '서울 강남구'
    if '서울숲' in addr_str or '성수' in addr_str: return '서울 성동구'
    
    # 5. 형식 검사: "시/도 + 띄어쓰기 + 구/군/시" 형태가 아니면 버림 (NaN 처리)
    # 정규식 패턴: '서울', '경기' 등 2글자 단어로 시작하고 띄어쓰기 후 '구', '시', '군'으로 끝나는 패턴
    # 예: ^(서울|경기|인천|부산|대구|광주|대전|울산|세종|강원|충북|충남|전북|전남|경북|경남|제주)\s+[가-힣]+(구|시|군)$
    # 단, '경기 성남시 분당구' 처럼 3단어인 경우도 허용하도록 유연하게 작성
    import re
    valid_pattern = r'^(서울|경기|인천|부산|대구|광주|대전|울산|세종|강원|충북|충남|전북|전남|경북|경남|제주)\s+[가-힣\s]+(구|시|군)$'
    
    if re.match(valid_pattern, addr_str):
        return addr_str # 완벽한 형태면 통과
    elif addr_str in ('서울', '경기', '부산', '대구', '인천', '광주', '대전', '울산', '제주'):
        # '서울', '경기' 처럼 광역단위만 있는 것도 살리고 싶다면 통과 (버리고 싶으면 np.nan)
        return addr_str
    else:
        # '3F, 343', '서울 장충단로' 등 패턴에 안 맞는 찌꺼기는 가차없이 버림
        return np.nan

# 새로운 컬럼에 최종 정제 결과 저장
df_wanted_na['location_perfect'] = df_wanted_na['location_final'].apply(final_polish)

# 의미 없는 데이터(NaN)를 아예 데이터프레임에서 삭제(Drop)
# 원격근무나 특정 지역 공고만 남습니다.
df_wanted_clean = df_wanted_na.dropna(subset=['location_perfect'])

print("=== 살아남은 완벽한 데이터 목록 ===")
print(df_wanted_clean['location_perfect'].unique())

print(f"\n버려진 데이터 수: {len(df_wanted_na) - len(df_wanted_clean)}개")

=== 살아남은 완벽한 데이터 목록 ===
['서울 서초구' '서울 강남구' '인천 연수구' '서울 마포구' '경기 수원시' '서울 구로구' '서울 영등포구' '서울 송파구'
 '서울 관악구' '서울 성동구' '경기 용인시' '서울 중구' '경기 성남시 수정구' '서울 용산구' '서울 강동구' '부산 중구'
 '서울 금천구' '경기 성남시 분당구' '대구 달성군' '원격근무' '경기 파주시' '서울 강서구' '서울 서대문구'
 '서울 종로구' '충남 천안시' '서울 동대문구' '경기 성남시 중원구' '경기 고양시' '경기 하남시' '서울 성북구'
 '경기 광명시' '전북 전주시' '서울 광진구' '경기 안산시' '부산 해운대구' '경기 남양주시' '경기 안양시' '인천 서구'
 '울산 중구' '경기 의왕시' '대전 유성구' '서울 양천구' '제주 제주시' '경기 과천시' '부산 남구' '대전 서구'
 '광주 북구' '경북 포항시' '부산 기장군' '경남 창원시' '인천 미추홀구' '서울 동작구' '대구 동구' '충북 청주시'
 '경기 김포시' '경기 화성시' '경기' '서울 도봉구' '대구 수성구' '부산 수영구' '경기 시흥시' '전북 군산시'
 '경기 군포시' '대구 북구' '서울' '경기 구리시' '경기 성남시' '부산 동구' '경기 이천시' '대구 서구' '인천 계양구'
 '부산 진구' '경기 평택시' '경기 부천시' '부산 영도구' '대구 달서구' '경북 경산시' '인천 부평구' '부산 북구'
 '광주 동구' '울산 남구' '대전 대덕구' '광주 서구']

버려진 데이터 수: 31개

In [67]:
df_wanted_clean.to_json('wanted_clean_location.json', force_ascii=False, orient='records')